/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/design/components/container/': RouteRecordInfo<'/design/components/container/', '/design/components/container', Record<never, never>, Record<never, never>>,
    '/design/components/designComponents/baseComponent/': RouteRecordInfo<'/design/components/designComponents/baseComponent/', '/design/components/designComponents/baseComponent', Record<never, never>, Record<never, never>>,
    '/design/components/designComponents/baseComponent/DesignCompWrapper': RouteRecordInfo<'/design/components/designComponents/baseComponent/DesignCompWrapper', '/design/components/designComponents/baseComponent/DesignCompWrapper', Record<never, never>, Record<never, never>>,
    '/design/components/designComponents/circle/': RouteRecordInfo<'/design/components/designComponents/circle/', '/design/components/designComponents/circle', Record<never, never>, Record<never, never>>,
    '/design/components/designComponents/square/': RouteRecordInfo<'/design/components/designComponents/square/', '/design/components/designComponents/square', Record<never, never>, Record<never, never>>,
    '/design/components/designComponents/text/': RouteRecordInfo<'/design/components/designComponents/text/', '/design/components/designComponents/text', Record<never, never>, Record<never, never>>,
    '/design/designPage/': RouteRecordInfo<'/design/designPage/', '/design/designPage', Record<never, never>, Record<never, never>>,
    '/design/viewPage/': RouteRecordInfo<'/design/viewPage/', '/design/viewPage', Record<never, never>, Record<never, never>>,
    '/formBuilderDemo': RouteRecordInfo<'/formBuilderDemo', '/formBuilderDemo', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>>,
    '/testAuth': RouteRecordInfo<'/testAuth', '/testAuth', Record<never, never>, Record<never, never>>,
    '/textEditor/': RouteRecordInfo<'/textEditor/', '/textEditor', Record<never, never>, Record<never, never>>,
  }
}
